<template>
	<div class="monsterinsights-container">
		<settings-block :title="text_title_export_import">
			<form action="" v-on:submit.prevent="submitForm">
				<label>
					<span class="monsterinsights-dark" v-text="text_import"></span>
					<span v-text="text_import_description"></span><settings-info-tooltip :content="text_import_tooltip" />
				</label>
				<div class="monsterinsights-file-input">
					<input type="file" v-on:change="handleFileUpload" />
				</div>
				<button type="submit" class="monsterinsights-button" v-text="text_import_button"></button>
				<label v-if="has_error" class="monsterinsights-error">
					<i class="monstericon-warning-triangle"></i><span v-html="text_has_error"></span>
				</label>
			</form>
			<div class="monsterinsights-separator"></div>
			<form action="" method="post">
				<label>
					<span class="monsterinsights-dark" v-text="text_export"></span>
					<span v-text="text_export_description"></span><settings-info-tooltip :content="text_export_tooltip" />
				</label>
				<input type="hidden" :value="nonce" name="monsterinsights_export_settings" />
				<input type="hidden" value="monsterinsights_export_settings" name="monsterinsights_action" />
				<button class="monsterinsights-button" v-text="text_export_button"></button>
			</form>
		</settings-block>
	</div>
</template>
<script>
	import { __ } from '@wordpress/i18n';
	import axios from 'axios';
	import SettingsBlock from '../../settings/components/SettingsBlock';
	import SettingsInfoTooltip from "../../settings/components/SettingsInfoTooltip";

	export default {
		name: 'ToolsTabImportExport',
		components: { SettingsInfoTooltip, SettingsBlock },
		data() {
			return {
				nonce: this.$mi.nonce,
				text_title_export_import: __('Import/Export', process.env.VUE_APP_TEXTDOMAIN),
				text_import: __('Import', process.env.VUE_APP_TEXTDOMAIN),
				text_import_description: __('Import settings from another MonsterInsights website.', process.env.VUE_APP_TEXTDOMAIN),
				text_export: __('Export', process.env.VUE_APP_TEXTDOMAIN),
				text_export_description: __('Export settings to import into another MonsterInsights install.', process.env.VUE_APP_TEXTDOMAIN),
				text_import_button: __('Import Settings', process.env.VUE_APP_TEXTDOMAIN),
				text_export_button: __('Export Settings', process.env.VUE_APP_TEXTDOMAIN),
				text_has_error: __('Please choose a file to import', process.env.VUE_APP_TEXTDOMAIN),
				text_import_tooltip: __( 'Use the filepicker below to select the settings export file from another site.', process.env.VUE_APP_TEXTDOMAIN ),
				text_export_tooltip: __( 'Use the button below to export a file with your MonsterInsights settings.', process.env.VUE_APP_TEXTDOMAIN ),
				has_error: false,
				selectedFile: false,
			};
		},
		methods: {
			handleFileUpload(event) {
				this.has_error = false;
				this.selectedFile = event.target.files[0];
			},
			submitForm() {
				const self = this;
				if (this.selectedFile) {
					this.$mi_loading_toast(__('Uploading file...', process.env.VUE_APP_TEXTDOMAIN));
					let formData = new FormData();
					formData.append('import_file', this.selectedFile);
					formData.append('action', 'monsterinsights_handle_settings_import');
					formData.append('nonce', this.$mi.nonce);

					axios.post(this.$mi.ajax, formData, {
						headers: {
							'Content-Type': 'multipart/form-data',
						},
					}).then(function(response) {
						if (response.data.success && response.data.data) {
							self.$store.commit('$_settings/SETTINGS_UPDATED', response.data.data);
							self.$swal({
								type: 'success',
								title: __('File imported', process.env.VUE_APP_TEXTDOMAIN),
								text: __('Settings successfully updated!', process.env.VUE_APP_TEXTDOMAIN),
								confirmButtonText: __('Ok', process.env.VUE_APP_TEXTDOMAIN),
							});
						} else {
							self.$swal({
								type: 'error',
								title: __('Error importing settings', process.env.VUE_APP_TEXTDOMAIN),
								text: __('Please choose a .json file generated by a MonsterInsights settings export.', process.env.VUE_APP_TEXTDOMAIN),
								confirmButtonText: __('Ok', process.env.VUE_APP_TEXTDOMAIN),
							});
						}
					});
				} else {
					this.has_error = true;
				}
			},
		},
	};
</script>

<style scoped>
    .monsterinsights-dark {
        display: block;
    }
</style>
